version: '3.8'

services:
  # Single container with ChromaDB + SQLite + FastAPI
  codebase-rag-minimal:
    build:
      context: .
      dockerfile: mvp/Dockerfile.single
    container_name: codebase-rag-minimal
    ports:
      - "8080:8080"
    environment:
      - MODE=single-container
      - LOG_LEVEL=INFO
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - DATABASE_URL=sqlite:///app/data/codebase.db
    volumes:
      # Mount your local repositories here
      - /path/to/your/repos:/app/repos:ro
      - ./logs:/app/logs
      - ./data:/app/data
    restart: unless-stopped
    mem_limit: 4g
    cpus: 2